M48
; DRILL file {KiCad 7.0.11} date Wed May 28 11:48:17 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-28T11:48:17+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1220
%
G90
G05
T1
X2.6421Y-1.0884
X2.8697Y-1.0884
T2
G00X-0.4389Y-0.8612
M15
G01X-0.4055Y-0.8278
M16
G05
M30
