M48
; DRILL file {KiCad 7.0.11} date Tue Jun 24 23:57:38 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-24T23:57:38+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1220
%
G90
G05
T1
X5.4Y-2.8585
X5.6276Y-2.8585
T2
X4.8465Y-3.3622
X4.8465Y-3.4803
T3
G00X5.0748Y-4.9262
M15
G01X5.1082Y-4.8927
M16
G05
M30
